Create Aries CS Engine
ubiquity/partnerships pull request #40
Opened 2023-07-03 17:24 UTC by Hodlatoor

Draft of W3F proposal upgrade with Aries Crowdsource Engine development and DevPool integration

Resolves #

2023-07-04 00:59 UTC, Hodlatoor commented
@pavlovcik can you take a look and confirm I covered all steps with this pull

2023-07-04 05:26 UTC, pavlovcik requested changes

2023-07-04 05:26 UTC, pavlovcik commented on partners/github/Aries Crowd Source Engine.html
You can delete this file

2023-07-04 05:26 UTC, pavlovcik commented on Aries CS Engine
You can delete this file

2023-07-04 05:26 UTC, pavlovcik commented on partners/github/Aries Crowd Source Engine.md
No need to also deliver as HTML because GitHub can display markdown perfectly fine. I'm not sure that it can even render HTML.

2023-07-04 05:26 UTC, pavlovcik commented on partners/github/Aries Crowd Source Engine.md
> +Milestone 3 (Aries DevPool related process optimization)
I would probably turn these into headers, so something like this

```suggestion
### Milestone 3 (Aries DevPool related process optimization)
```

2023-07-04 05:26 UTC, pavlovcik commented on partners/github/Aries Crowd Source Engine.md
> +*also available as finished html file in repo
```suggestion
```

2023-07-04 05:28 UTC, pavlovcik commented
Pro tip: 

Take a look at the "Files changed" tab for context on where my comments are in relation to the corpus. However because this review is simple enough, you might be able to get by entirely on the "Conversation" tab

2023-07-28 08:08 UTC, Hodlatoor reviewed
removed html file

2023-07-28 08:08 UTC, closed without merging